### ISSUE TITLE
Newsletter Info Form

### ISSUE THREAD

**Issue by denzelb5** [nss-evening-cohort-10/foundations-group-project-sore-throat#13]
# User Story:

As a user, I want to be able to enter my name and email to sign up for the band newsletter.

# AC:

WHEN: The page loads,
THEN: a form should appear with 2 input boxes for name and email.  There should be a submit button to submit the information.

# Dev Notes:

Use bootstrap form.  
Two input boxes, name and email.
One 'submit' button.

**Comment by zoeames** [comment]
what happens when you click the submit button?

**Comment by denzelb5** [comment]
![image](https://user-images.githubusercontent.com/38984447/65088342-975be700-d97e-11e9-9fcf-5110ab5dc861.png)
