### ISSUE TITLE
newsletter cards

### ISSUE THREAD

**Issue by denzelb5** [nss-evening-cohort-10/foundations-group-project-sore-throat#2]
# User Story:
 
As a user, I want to see cards that display info on recent and upcoming events organized by date  and name.  There should be a brief description with a link at the bottom to opt to read more.

# AC:

A card should display with a date, time, and info about the event.  A button at the bottom should link to a page with more info.

# Dev notes:

Use bootstrap.
Link should create an expanded card.

**Comment by denzelb5** [comment]
![image](https://user-images.githubusercontent.com/38984447/64999902-1550bd00-d8af-11e9-8dfa-593bd71d365b.png)

**Comment by zoeames** [comment]
make a separate ticket for the read more links
