### ISSUE TITLE
Create Wireframes

### ISSUE THREAD

**Issue by broach44** [nss-evening-cohort-10/foundations-group-project-sore-throat#4]
# User Story
As a developer, when I start a project I like to see what it will look like.

# AC
**WHEN** I open this ticket
**THEN** I should see screenshots for each page

# Dev Notes
- Use moqups to generate wireframes for each page
- Paste them into the comment sections of this ticket

**Comment by broach44** [comment]
# Bio Page:  

file name = bio.html

![image](https://user-images.githubusercontent.com/51486216/64925338-9a0ae080-d7b4-11e9-895c-92b64154780d.png)

**Comment by broach44** [comment]
Fonts: 
Headings - Permanent Marker - https://fonts.google.com/specimen/Permanent+Marker
Other text - Roboto - https://fonts.google.com/specimen/Roboto

Color Scheme:
Background color:  202020;
Lighter black:  313131;
Bright Pink:  ff0078;
Purple:  bd14db;
White:  ffffff;

**Comment by aleshakay** [comment]
filename = merchandise.html

![image](https://user-images.githubusercontent.com/39807157/64931379-efb7ab00-d7fd-11e9-94b3-4218a247debc.png)

**Comment by williaj615** [comment]
# Home Page

<img width="465" alt="Screen Shot 2019-09-16 at 7 23 43 PM" src="https://user-images.githubusercontent.com/47404655/65002028-9c099800-d8b7-11e9-92fe-42f0f7eaf05a.png">

**Comment by denzelb5** [comment]
file name = news.html

![image](https://user-images.githubusercontent.com/38984447/64999979-76789080-d8af-11e9-81f7-612601c343a1.png)
